"""2044

Revision ID: 09800e5d548d
Revises: c97be29d9f7a
Create Date: 2024-09-21 20:45:04.130076

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '09800e5d548d'
down_revision = 'c97be29d9f7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', postgresql.BYTEA(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
