"""2049

Revision ID: 84f6c394ecc4
Revises: 09800e5d548d
Create Date: 2024-09-21 21:49:30.186490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84f6c394ecc4'
down_revision = '09800e5d548d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('snippet',
               existing_type=sa.TEXT(),
               type_=sa.String(length=250),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('snippet',
               existing_type=sa.String(length=250),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
