""" Добавление фото в базу данных 

Revision ID: c0f397c5a5c9
Revises: 84f6c394ecc4
Create Date: 2024-09-23 11:44:02.560318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0f397c5a5c9'
down_revision = '84f6c394ecc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.PickleType(), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=350),
               existing_nullable=False)
        batch_op.alter_column('snippet',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=350),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('snippet',
               existing_type=sa.String(length=350),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=350),
               type_=sa.VARCHAR(length=250),
               existing_nullable=False)
        batch_op.drop_column('image')

    # ### end Alembic commands ###
